#!/bin/bash

export XDG_DATA_HOME=${XDG_DATA_HOME:-/usr/share/}
x_xdg_dirs="/usr/share/:$XDG_DATA_DIRS"
x_xdg_dir=
x_def_icon_theme=icons/hicolor

function x_init()
{
	return;
}

function x_prerm_upgrade()
{
	return;
}

function x_prerm_remove()
{
	return;
}

function x_main()
{
	if [ $# -eq 0 ] ; then
		return;
	fi

	x_init
	case $1 in
		remove )
			shift
			x_prerm_remove $@
			;;
		upgrade )
			shift
			x_prerm_upgrade $@
			;;
		failed-upgrade )
			;;
	esac
}

x_main $@

